### ISSUE TITLE
Schematic symbols missing

### ISSUE THREAD

**Issue by JustAnother1** [pluggee/R1000AX#15]
I tried to open the schematic on Kicad 4.0.6 and get a lot of error messages regarding missing symbols / libraries. I then also see only one page. Is that the complete schematic?

Maybe you could provide a PDF of the crowd supply version?

**Comment by pluggee** [comment]
@JustAnother1 , can you clone KiCADLibs and set it up as instructed in Readme.md

**Comment by pluggee** [comment]
@JustAnother1 , updating Readme.md with proper instructions, stay tuned

**Comment by pluggee** [comment]
@JustAnother1 , updated Readme.md, please try again and tell me if you have any trouble

**Comment by pluggee** [comment]
@JustAnother1 , added schematics PDF for your convenience
